config/routes.rb
Rails.application.routes.draw do

  resources :resumes

  resources :homes

  resources :money

  resources :tips

  resources :locations

  resources :videos

  resources :madlibs

  resources :blogs

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params[:video]
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

<div class="example" id="hulu">
      <h3>Orel Learns Much Foundation Presents: </h3>
      <div class="ie-fix"><div type="text" id="hulu-target" class="target">AJAX</div></div>
      <div id="hulu-content">
        <b>OrelPresents:</b> AJAX and Eternity<br />
        Season 1, Ep. 1 (00:48)<br />
        Air date: 05/20/2009  |  Rated: TV-14  |  ☆☆☆☆☆<br />
        <hr />
        In this episode, I'll discuss the idea behind Asynchronous Javascript, its history, its current implementation, and how to acheive eternal web development salvation
      </div>
      <div class="desc">
        <p><a href="https://resume.creddle.io/resume/5gi4t3n016i">My Resume</a> style. If you would like to hire me to do things, please click on this link and verify the things I have done are the things that you seek</p>
        <div class="source">
          <div class="js">$('#hulu-content').hide();
$('#hulu-target').bt({
  contentSelector: "$('#hulu-content')",
  positions: ['right', 'left'],
  fill: '#F4F4F4',
  strokeStyle: '#666666', 
  spikeLength: 20,
  spikeGirth: 10,
  width: 350,
  overlap: 0,
  centerPointY: 1,
  cornerRadius: 0, 
  cssStyles: {
    fontFamily: '"Lucida Grande",Helvetica,Arial,Verdana,sans-serif', 
    fontSize: '12px',
    padding: '10px 14px'
  },
  shadow: true,
  shadowColor: 'rgba(0,0,0,.5)',
  shadowBlur: 8,
  shadowOffsetX: 4,
  shadowOffsetY: 4
});</div>
        </div>
      </div>
    </div>


<iframe width="560" height="315" src="https://www.youtube.com/embed/O-aBYxQ9yB0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>



/Users/apple/Documents/GitHub/personal_website
<iframe width="560" height="315" src="https://www.youtube.com/embed/Jd1diAuVMZo" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>